name: Deploy to EC2

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
  push:
    branches:
      - main
      - develop

jobs: # ì•„ë˜ì˜ jobsë¥¼ ìˆ˜í–‰

  ci:
    name: "ğŸ”§ CI: Build & Prepare"
    runs-on: ubuntu-latest # ì—¬ëŸ¬ OS ì¤‘ ìš°ë¶„íˆ¬ í™˜ê²½ ì„ íƒ

    steps:
    - name: ğŸ›ï¸ Checkout source code # 1. ë§ˆìŠ¤í„° ë¸Œëœì¹˜ë¡œ checkout
      uses: actions/checkout@v3

    - name: ğŸ—ï¸ Create .env file from GitHub Secrets # 2. ê¹ƒí—™ settings > secrets ì— ì˜¬ë ¤ë†“ì€ ë¹„ë°€ ê°’ì„ ë³µì‚¬í•´ .env íŒŒì¼ë¡œ ìƒì„±
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env

    - name: ğŸ“ Create remote directory on EC2 # 3. ec2 ì„œë²„ì— ì ‘ì†í•´ ë¦¬ëª¨íŠ¸ ë””ë ‰í† ë¦¬ ìƒì„±
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: mkdir -p /home/ubuntu/srv/ubuntu

    - name: ğŸ“¤ Sync source code to EC2 # 4. ssh keyë¡œ í˜„ì¬ í‘¸ì‹œëœ ì†ŒìŠ¤ë¥¼ ì„œë²„ì— ë³µì‚¬ (rsyncë¡œ github runnersì™€ ec2 ë™ê¸°í™”)
      uses: burnett01/rsync-deployments@4.1
      continue-on-error: true
      with:
        switches: -avzr --no-perms --delete --ignore-errors
        remote_path: /home/ubuntu/srv/ubuntu/
        remote_host: ${{ secrets.HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.KEY }}

  cd:
    name: "ğŸš€ CD: Deploy to EC2"
    runs-on: ubuntu-latest
    needs: ci # CI ë‹¨ê³„ê°€ ëë‚œ í›„ ì‹¤í–‰ë¨

    steps:
    - name: ğŸ” Run deploy.sh on EC2 # 5. EC2ì—ì„œ ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          chmod +x /home/ubuntu/srv/ubuntu/config/scripts/deploy.sh
          sh /home/ubuntu/srv/ubuntu/config/scripts/deploy.sh
